name: Tests the build of the extension

on:
  # Run on any PR that targets the master branch
  pull_request:
    branches: [ master ]

  # Allow manual runs from the Actions tab
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      # 1 – Check out the code
      - uses: actions/checkout@v2

      # 2 – Expose the version tag as $PACKAGE_VERSION
      - name: Set environment package version from tag
        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/*/v}" >> "$GITHUB_ENV"

      # 3 – Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 4 – Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # 5 – Set up JDK 11 (adopt) and enable the sbt cache
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'sbt'

      # 6 – Install a recent sbt launcher
      - name: Set up sbt
        uses: sbt/setup-sbt@v1
        with:
          sbt-version: '1.9.9'

      # 7 – Install Python build / publish deps
      - name: Install Python dependencies
        run: pip install build twine

      # 8 – Build the wheel
      - name: Build wheel
        run: python -m build

