name: Tests the build of the extension

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set environnment package version from tag
      run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV # extract "1.2.3" from refs/tags/v1.2.3
      
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
   
    - name: Set up JDK 11
      uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
          cache: sbt
          - uses: sbt/setup-sbt@v1
            with:
              sbt-runner-version: 1.9.9

    - name: Install dependencies 
      run: pip install build twine

    - name: Build wheel
      run: python -m build