# This is a basic workflow to help you get started with Actions

name: Pull Request Checks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
          cache-dependency-path: yarn.lock
          
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x
      
      - name: Install Jupyterlab
        run: pip install jupyterlab==4

      - name: Install JS dependencies
        run: jlpm install --immutable

      - name: "JavaScript Checks"
        run: jlpm check:all
